### ISSUE TITLE
glue is not compatible with python 3.11 Error on installation.

### ISSUE THREAD

**Issue by olenamarchenko1234** [gluesolutions/glue-genes#25]
Collecting numba>=0.41.0
  Downloading numba-0.56.4.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 7.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/h8/9wx5_3sj4vl4l049xbxkfvnm0000gp/T/pip-install-_n417ok6/numba_9ebfefc40ca94e48a7b1e97af191f0d6/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/h8/9wx5_3sj4vl4l049xbxkfvnm0000gp/T/pip-install-_n417ok6/numba_9ebfefc40ca94e48a7b1e97af191f0d6/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by jfoster17** [comment]
Yeah, this is sort of doing the right thing, in that numba currently does not work with Python 3.11 (https://github.com/numba/numba/issues/8304). But we should gate glue genes so that it's clear that it won't work.

**Comment by jfoster17** [comment]
This has been fixed in numba and now works.
