### ISSUE TITLE
PyQt6 breaks menubar plugins

### ISSUE THREAD

**Issue by jfoster17** [gluesolutions/glue-genes#29]
```
Traceback (most recent call last):
  File "/Users/jfoster/Developer/pancreas-spaceranger/glue-extended-components-PR2373/glue/utils/misc.py", line 55, in result
    return func(*args, **kwargs)
  File "/Users/jfoster/Developer/pancreas-spaceranger/glue-genes-spaceranger-PR24/glue_genes/glue_single_cell/menubar_plugin.py", line 16, in pca_subset_exp_plugin
    PCASubsetDialog.summarize(data_collection, default=None, parent=None)
  File "/Users/jfoster/Developer/pancreas-spaceranger/glue-genes-spaceranger-PR24/glue_genes/glue_single_cell/qt/pca_subset.py", line 317, in summarize
    self = cls(collect, parent=parent, default=default)
  File "/Users/jfoster/Developer/pancreas-spaceranger/glue-genes-spaceranger-PR24/glue_genes/glue_single_cell/qt/pca_subset.py", line 250, in __init__
    self.ui = load_ui("pca_subset.ui", self, directory=os.path.dirname(__file__))
  File "/Users/jfoster/Developer/pancreas-spaceranger/glue-extended-components-PR2373/glue/utils/qt/helpers.py", line 143, in load_ui
    return loadUi(full_path, parent)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/load_ui.py", line 86, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/Loader/loader.py", line 62, in loadUi
    return self.parse(filename)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 1014, in parse
    self._handle_widget(ui_file.widget)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 842, in _handle_widget
    self.traverseWidgetTree(el)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 512, in createLayout
    self.traverseWidgetTree(elem)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 555, in handleItem
    self.traverseWidgetTree(elem)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 818, in traverseWidgetTree
    handler(self, child)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 271, in createWidget
    self.stack.push(self._setupObject(widget_class, parent, elem))
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/uiparser.py", line 237, in _setupObject
    self.wprops.setProperties(obj, branch)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/properties.py", line 430, in setProperties
    prop_value = self.convert(prop, widget)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/properties.py", line 393, in convert
    return func(prop[0], **args)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/properties.py", line 141, in _enum
    return self._pyEnumMember(prop.text)
  File "/Users/jfoster/mambaforge/envs/pancreas-spaceranger-dev/lib/python3.10/site-packages/PyQt6/uic/properties.py", line 127, in _pyEnumMember
    scope = getattr(scope, tail)
AttributeError: type object 'QComboBox' has no attribute 'AdjustToMinimumContentsLength'. Did you mean: 'setMinimumContentsLength'?
```

This seems to be a problem under PyQt6 only, and not PyQt5. Maybe updating the UI components with Qt Designer for PyQt6 will fix this? https://www.pythonguis.com/installation/install-qt-designer-standalone/

**Comment by jfoster17** [comment]
Fixed in v1.1.0
